#!/usr/bin/env python3
"""
Setup script for PutsEngine Email Reports.

This script helps you configure email settings for daily 3 PM reports.

USAGE:
    python setup_email.py

REQUIREMENTS:
    - Gmail account with 2-Step Verification enabled
    - Gmail App Password (not your regular password)

To generate Gmail App Password:
    1. Go to https://myaccount.google.com/security
    2. Enable 2-Step Verification (if not already)
    3. Go to "App passwords" (search for it)
    4. Select "Mail" and "Other (Custom name)" -> "PutsEngine"
    5. Copy the 16-character password
"""

import os
from pathlib import Path


def main():
    print("=" * 60)
    print("🏛️ PUTSENGINE EMAIL SETUP")
    print("=" * 60)
    print()
    print("This will configure daily 3 PM EST email reports with best picks.")
    print()
    
    # Check if .env file exists
    env_file = Path(".env")
    existing_vars = {}
    
    if env_file.exists():
        print("📄 Found existing .env file")
        with open(env_file, "r") as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    key, value = line.strip().split("=", 1)
                    existing_vars[key] = value
    
    # Get email settings
    print()
    print("Please enter your email settings:")
    print("(Press Enter to keep existing value)")
    print()
    
    # Sender email
    current_sender = existing_vars.get("PUTSENGINE_EMAIL_SENDER", "")
    sender = input(f"Gmail address to send FROM [{current_sender or 'not set'}]: ").strip()
    if not sender and current_sender:
        sender = current_sender
    
    # App password
    current_password = existing_vars.get("PUTSENGINE_EMAIL_PASSWORD", "")
    password_display = "*" * 16 if current_password else "not set"
    password = input(f"Gmail App Password [{password_display}]: ").strip()
    if not password and current_password:
        password = current_password
    
    # Recipient email
    current_recipient = existing_vars.get("PUTSENGINE_EMAIL_RECIPIENT", "")
    recipient = input(f"Email address to send TO [{current_recipient or 'not set'}]: ").strip()
    if not recipient and current_recipient:
        recipient = current_recipient
    
    # Validate
    if not all([sender, password, recipient]):
        print()
        print("❌ Missing required fields. Please provide all values.")
        return
    
    # Update .env file - APPEND email settings without overwriting API keys
    # Read existing content first
    existing_content = ""
    if env_file.exists():
        with open(env_file, "r") as f:
            existing_content = f.read()
    
    # Remove old email settings if present
    lines = existing_content.split('\n')
    filtered_lines = []
    for line in lines:
        if not line.startswith('PUTSENGINE_EMAIL') and not line.startswith('PUTSENGINE_SMTP'):
            # Also skip comment lines about email config
            if 'Gmail' not in line and 'App Password' not in line and 'setup_email.py' not in line:
                filtered_lines.append(line)
    
    # Rebuild content without email settings
    base_content = '\n'.join(filtered_lines).strip()
    
    # Add email settings
    email_content = f"""

# PutsEngine Email Configuration
# Generated by setup_email.py

# Gmail sender (your Gmail address)
PUTSENGINE_EMAIL_SENDER={sender}

# Gmail App Password (NOT your regular password)
# Generate at: https://myaccount.google.com/apppasswords
PUTSENGINE_EMAIL_PASSWORD={password}

# Recipient email (where reports go)
PUTSENGINE_EMAIL_RECIPIENT={recipient}

# SMTP settings (Gmail defaults)
PUTSENGINE_SMTP_SERVER=smtp.gmail.com
PUTSENGINE_SMTP_PORT=587
"""
    
    final_content = base_content + email_content if base_content else email_content.strip()
    
    with open(env_file, "w") as f:
        f.write(final_content)
    
    print()
    print("✅ Email configuration saved to .env file")
    print()
    
    # Set environment variables for current session
    os.environ["PUTSENGINE_EMAIL_SENDER"] = sender
    os.environ["PUTSENGINE_EMAIL_PASSWORD"] = password
    os.environ["PUTSENGINE_EMAIL_RECIPIENT"] = recipient
    
    # Ask to send test email
    print("Would you like to send a test email now?")
    test = input("Send test? [y/N]: ").strip().lower()
    
    if test == "y":
        print()
        print("Sending test email...")
        
        # Load current scan results
        import json
        from putsengine.email_reporter import send_email_report, save_report_to_file
        
        try:
            with open("scheduled_scan_results.json", "r") as f:
                results = json.load(f)
            
            # Save report first
            report_path = save_report_to_file(results)
            print(f"📄 Report saved: {report_path}")
            
            # Send email
            success = send_email_report(results)
            
            if success:
                print()
                print("✅ Test email sent successfully!")
                print(f"   Check your inbox at: {recipient}")
            else:
                print()
                print("❌ Email failed. Check your App Password and Gmail settings.")
                print("   Make sure 2-Step Verification is enabled.")
                
        except FileNotFoundError:
            print("❌ No scan results found. Run a scan first:")
            print("   python start_putsengine.py --scan-now")
        except Exception as e:
            print(f"❌ Error: {e}")
    
    print()
    print("=" * 60)
    print("SETUP COMPLETE")
    print("=" * 60)
    print()
    print("📧 Daily reports will be sent at 3 PM EST")
    print()
    print("To start the scheduler with email reports:")
    print("   python3 start_putsengine.py --dashboard")
    print()
    print("To manually send a report now:")
    print("   python3 -c \"import asyncio; from putsengine.email_reporter import run_daily_report_scan; asyncio.run(run_daily_report_scan())\"")
    print()


if __name__ == "__main__":
    main()
